version: '2'
services:
    db:
      image: mysql
      ports:
       - "3306:3306"
      volumes:
       - ./:/var/www
       - ./provision/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=root
